---
title: "Analysis_bigterm"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(readr)
library(stringr)
library(ggplot2)
library(ggpmisc)
```

```{r}
### load and preprocess experiment data (barcode count files)
# input:        character or connection; data file with input read counts
# dark:         character or connection; data file with output read counts from dark condition
# light:        optional; character or connection; data file with output read counts from light condition (only available for tobacco leaf system)
# subassembly:  R object; subassembly data frame
# rcc:          numeric vector with two or three elements; read count cutoffs to be applied to the input and output;
#               first element: cutoff for input; second element: cutoff for output 'dark'; third element: cutoff for output 'light' (uses second element if no third element given)
load_experiment <- function(input, light, dark = NA, subassembly, rcc = c(1, 1, 1)) {
  
  # configure read count cutoff
  if (length(rcc) == 2) {
    rcc[3] <- rcc[2]
  } else if (length(rcc) != 3 | ! is.numeric(rcc)) {
    stop('rcc must contain two to three numeric values')
  }
  
  # load and merge files (only keep barcodes detected in both input and output)
  data_inp <- read_table2(input, col_names = c('count', 'barcode'))
  
  data_both <- read_table2(light, col_names = c('count', 'barcode')) %>%
    inner_join(data_inp, by = 'barcode', suffix = c('_out', '_inp')) %>%
    mutate(
      light = FALSE
    )
  
  # add 'light' data if supplied
  if (! is.na(dark)) {
    data_light <- read_table2(light, col_names = c('count', 'barcode')) %>%
      inner_join(data_inp, by = 'barcode', suffix = c('_out', '_inp')) %>%
      mutate(
        light = TRUE
      )
    
    data_both <- bind_rows(data_both, data_light)
  }
  
  # merge with subassembly
  data_both <- inner_join(data_both, subassembly, by = 'barcode')
  
  # read count cutoff
  data_both <- data_both %>%
    filter(
      (count_inp >= rcc[1]) & (count_out >= if_else(light, rcc[3], rcc[2]))
    )
  
  # aggregate barcodes (sum of individual counts)
  data_both <- data_both %>%
    group_by(across(-any_of(c('count_inp', 'count_out', 'barcode')))) %>%
    summarise(
      n_bc = n(),
      count_inp = sum(count_inp),
      count_out = sum(count_out)
    ) %>%
    ungroup()
  
  # calculate enrichment
  data_both <- data_both %>%
    group_by(light) %>%
    mutate(
      enrichment = log2((count_out / sum(count_out)) / (count_inp / sum(count_inp)))
    ) %>%
    ungroup()
  
  # return result
  return(data_both)
}
```

```{r}
### load subassembly
subassembly <- read_tsv('subassembly/subassembly_genomic_terminators_filtered.tsv.gz') 
```

```{r}
nbc_tobacco <- subassembly %>%
  filter(variant=="WT") %>% 
  group_by(id) %>%
  count() %>%
  ungroup() %>%
  rename(n_bc = n)
```




```{r}
### load experiment data
reps <- c('1', '2')
```


```{r}
subassembly
```

```{r}
data_all <- expand_grid('rep' = reps) %>%
  nest_by(across(everything())) %>%
  summarise(
    load_experiment(
      input = paste0('data/barcode_counts/rep', str_sub(rep, 1, 1), '/barcode_pPSt_35Senh-35Spr-GFP-term_', as.roman(str_sub(rep, 1, 1)), '_input.count.gz'),
      light = paste0('data/barcode_counts/rep', str_sub(rep, 1, 1), '/barcode_pPSt_35Senh-35Spr-GFP-term_', as.roman(str_sub(rep, 1, 1)), if_else(nchar(rep) > 1, str_sub(rep, 2), ''), '_Light.count.gz'),
     # light = ifelse(rep == '2', NA, paste0('rep', str_sub(rep, 1, 1), '/barcode_pPSt_enh-35Spr-eGFP-term_', as.roman(str_sub(rep, 1, 1)), if_else(nchar(rep) > 1, str_sub(rep, 2), ''), '_light.count.gz')),
      subassembly = subassembly,
      rcc = c(5, 5, 5)
    )
  ) %>%
  ungroup()
```

```{r}
data_all %>% count(truncation)
```

```{r}
data_all <- data_all %>% filter(variant=="WT" & is.na(truncation))
```


```{r}
### normalize to WT t35S construct (most abundant terminator in library)
data_all <- data_all %>%
  group_by(rep, light) %>%
  mutate(
    enrichment = enrichment - enrichment[variant == 'WT' & id == 't35S']
  ) %>%
  ungroup()
```

```{r}
data_all %>% filter(id=='t35S')
```


```{r}
data_mean <- data_all %>%
  group_by(light,id,variant,GC,length) %>%
  summarise(
    enrichment = mean(enrichment)
  ) %>%
  ungroup()
```

```{r}
data_mean
```

```{r}
data_all
```


```{r}
#save(data_seq, file = 'RData/data_seq.Rdata')
save(data_all, file = 'RData/data_all.Rdata')
save(data_mean, file = 'RData/data_mean.Rdata')
```






